#if !canImport(ObjectiveC)
import XCTest

extension NetworkTets {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NetworkTets = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(NetworkTets.__allTests__NetworkTets),
    ]
}
#endif
